# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_lastname', models.CharField(max_length=200)),
                ('person_role', models.CharField(max_length=200)),
                ('person_birthday', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('PR', 'Print'), ('DS', 'Design'), ('CO', 'Coding'), ('HU', 'Human')], default='CO', max_length=2)),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_description', models.CharField(max_length=200)),
                ('skill_icon', models.CharField(max_length=200)),
                ('skill_rating', models.IntegerField(default=0)),
                ('skill_category', models.CharField(max_length=200)),
            ],
        ),
    ]
