# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_auto_20160802_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
