# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_auto_20160802_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_category',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_description',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_icon',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='subcategory',
        ),
    ]
