# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_auto_20160803_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
