# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0009_auto_20160804_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='MyContent',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
