# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0012_mycontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyContent',
        ),
    ]
