# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0018_delete_foo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontent',
            name='h1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mycontent',
            name='h1_it',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mycontent',
            name='h2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mycontent',
            name='h2_it',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mycontent',
            name='image_primary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mycontent',
            name='image_secondary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mycontent',
            name='layout_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='subcategory',
            field=models.CharField(max_length=255),
        ),
    ]
