# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0020_auto_20160804_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PR', 'Print'), ('DS', 'Design'), ('CO', 'Coding'), ('HU', 'Human'), ('SC', 'School')], default='SC', max_length=2)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_it', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('description_it', models.TextField(max_length=5000)),
                ('body_it', models.TextField(max_length=5000)),
                ('layout_class', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PR', 'Print'), ('DS', 'Design'), ('CO', 'Coding'), ('HU', 'Human')], default='CO', max_length=2)),
                ('h1', models.CharField(blank=True, max_length=255)),
                ('h2', models.CharField(blank=True, max_length=255)),
                ('h1_it', models.CharField(blank=True, max_length=255)),
                ('h2_it', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('description_it', models.TextField(max_length=5000)),
                ('body_it', models.TextField(max_length=5000)),
                ('layout_class', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='description_it',
            field=models.TextField(default='work in progress', max_length=5000),
            preserve_default=False,
        ),
    ]
