# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0021_auto_20160805_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='JobHistory',
            new_name='Job',
        ),
    ]
