# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0023_auto_20160805_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('PR', 'Print'), ('DS', 'Design'), ('CO', 'Coding'), ('OT', 'Human')], default='CO', max_length=2),
        ),
    ]
