# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0024_auto_20160806_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='h2',
            new_name='excerpt',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='h2_it',
            new_name='excerpt_it',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='h1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='h1_it',
            new_name='name_it',
        ),
    ]
