# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0026_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
