# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0027_person_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unavailable_msg',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='unavailable_msg_it',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
