# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0029_auto_20160812_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('featured_image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('article_image1', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('article_image2', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tag', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=5000)),
            ],
        ),
    ]
