# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0031_auto_20160823_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='article_image1',
            field=models.FileField(upload_to='mysite/media/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='article_image2',
            field=models.FileField(upload_to='mysite/media/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.FileField(upload_to='mysite/media/uploads/%Y/%m/%d/'),
        ),
    ]
