# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0032_auto_20160823_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
