# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0033_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('TC', 'Technology'), ('LF', 'Life'), ('CS', 'Courses'), ('CD', 'Coding')], default='LF', max_length=2)),
                ('featured_image', models.FileField(upload_to='mysite/media/uploads/%Y/%m/%d/')),
                ('article_image1', models.FileField(upload_to='mysite/media/uploads/%Y/%m/%d/')),
                ('article_image2', models.FileField(upload_to='mysite/media/uploads/%Y/%m/%d/')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tag', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=5000)),
            ],
        ),
    ]
