# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:48
from __future__ import unicode_literals

from django.db import migrations
import django_filepicker.models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0037_auto_20160824_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image1',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='article_image2',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
    ]
