# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:25
from __future__ import unicode_literals

from django.db import migrations
import django_filepicker.models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0038_auto_20160824_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontent',
            name='image_primary',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
        migrations.AlterField(
            model_name='mycontent',
            name='image_secondary',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
    ]
