# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0039_auto_20160826_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='captcha',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
