# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_filepicker.models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0042_mycontent_video_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('category', models.CharField(choices=[('TC', 'Technology'), ('LF', 'Life'), ('CS', 'Courses'), ('CD', 'Coding')], default='LF', max_length=2)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('featured_image', django_filepicker.models.FPUrlField(blank=True)),
                ('article_image1', django_filepicker.models.FPUrlField(blank=True)),
                ('article_image2', django_filepicker.models.FPUrlField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tag', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
    ]
