# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0043_auto_20170221_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thought',
        ),
    ]
