# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_filepicker.models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0044_delete_thought'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_image3',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image4',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image5',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image6',
            field=django_filepicker.models.FPUrlField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('PR', 'Print'), ('DS', 'Design'), ('CO', 'Programming'), ('HU', 'Other'), ('SC', 'School')], default='SC', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('PR', 'Print'), ('DS', 'Design'), ('CO', 'Programming'), ('OT', 'Other')], default='CO', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TC', 'Technology'), ('LF', 'Life'), ('CS', 'Courses'), ('CD', 'Programming')], default='LF', max_length=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('PR', 'Print'), ('DS', 'Design'), ('CO', 'Programming'), ('HU', 'Other')], default='CO', max_length=2),
        ),
    ]
